name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        qt-version: [ '6.2.0' ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-Qt${{ matrix.qt-version }}-cache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.11.1
      with:
        version: '6.2.0'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        aqtversion: ==1.2.0b3 # <1.2.0 has problem with osx installation of Qt 6
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
          sudo apt-get install llvm
        fi

        python -m pip install --upgrade pip
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py > poetry.py
        python3 poetry.py --version 1.2.0a1
        echo "$HOME/.local/bin" >> $GITHUB_PATH

        if [ "${{ matrix.os }}" == "macos-10.15" ]; then
          # is needed for macos to make poetry available
          export PATH="/Users/runner/.local/bin:$PATH"

          # qt on macos is installed in framework mode, includes like 'QtCore/QUrl' cannot be resolved by default
          ln -sf $Qt6_DIR/lib/QtCore.framework/Versions/A/Headers/* $Qt6_DIR/lib/QtCore.framework/Versions/A/Headers/6.2.0/QtCore/
          ln -sf $Qt6_DIR/lib/QtGui.framework/Versions/A/Headers/* $Qt6_DIR/lib/QtGui.framework/Versions/A/Headers/6.2.0/QtGui/
          ln -sf $Qt6_DIR/lib/QtNetwork.framework/Versions/A/Headers/* $Qt6_DIR/lib/QtNetwork.framework/Versions/A/Headers/6.2.0/QtNetwork/
        fi

        poetry install --verbose
        poetry run pip3 install PySide6 # temporary workaround, poetry can't install PySide6. TODO: investigate
        git clone https://github.com/quotient-im/libQuotient.git PyQuotient/libQuotient
    
    - name: Build
      run: |
        mkdir -p build
        pushd build
        cmake -DBUILD_TESTING=OFF -DBUILD_WITH_QT6=ON -DQT_PATH=$Qt6_DIR -DPYTHON_ENV_VERSION=3.9 ../
        make
        popd
    
    - name: Run unit tests
      run: |
        poetry run pytest
